### PR TITLE
Add more improvements about l10n

### PR DESCRIPTION
**Pull request by macagua**
- Add Transifex.net service integration to manage the translation process.
- Add Spanish translation
- Update README file
- Fixed some typos
- Updated gettext files support

### CODE REVIEW

**Comment by macagua** [comment]
Hi @keul  

Can you review this pull request, if all ok can merge it?

Thank you

**Comment by keul** [comment]
HTTP/1.1 301 Moved Permanently
Location: @cekk

**Comment by cekk** [comment]
Thank you @macagua LGTM

**Comment by cekk** [comment]
@macagua released!

**Comment by macagua** [comment]
@cekk Thanks you! ^_^

**Pull request merged**
